services:
  # Immich - Self-hosted Photo and Video Management
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION_PIN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    depends_on:
      immich-postgresql:
        condition: service_healthy
      immich-redis:
        condition: service_healthy
      immich-machine-learning:
        condition: service_started
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    healthcheck:
      disable: false
    networks:
      - default
    ports:
      - $IMMICH_PORT:2283
    volumes:
      - ${IMMICH_FOLDER}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${IMMICH_POSTGRESQL_PASSWORD}
      DB_HOSTNAME: immich-postgresql
      DB_USERNAME: immich_db_user
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich-redis
    # DOCKER-LABELS-PLACEHOLDER
