#!/bin/bash
# n8n Pre-Install Hook
# Injects PostgreSQL password into n8n compose via sed placeholder
# Pattern: same as Langfuse — secret file stays root:root 0600,
# hook reads it with sudo and injects into compose before container start

COMPOSE_DIR="$DOCKER_FOLDER/compose/$HOSTNAME"

# Read the secret (generated by f_process_app_secrets)
POSTGRESQL_PASSWORD=$(sudo cat "$DOCKER_FOLDER/secrets/n8n_postgresql_password" 2>/dev/null)

if [[ -z "$POSTGRESQL_PASSWORD" ]]; then
    f_print_error "n8n PostgreSQL password missing from $DOCKER_FOLDER/secrets/"
    log_error "n8n" "Missing secret: n8n_postgresql_password - aborting pre-install"
    return 1
fi

# Inject into main n8n compose
local n8n_compose="$COMPOSE_DIR/n8n.yml"
if [[ -f "$n8n_compose" ]]; then
    f_print_substep "Injecting database password into n8n compose..."
    sudo sed -i "s|N8N-POSTGRESQL-PASSWORD-PLACEHOLDER|$POSTGRESQL_PASSWORD|g" "$n8n_compose"
    log_info "n8n" "Injected PostgreSQL password into n8n.yml"
fi

f_print_success "n8n secrets configured"
