services:
  # Supabase Studio - Dashboard UI
  supabase:
    image: supabase/studio:${SUPABASE_VERSION_PIN}
    container_name: supabase
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: [ "apps", "all" ]
    networks:
      - default
    environment:
      - HOSTNAME=0.0.0.0
      - STUDIO_PG_META_URL=http://supabase-meta:8080
      - POSTGRES_HOST=supabase-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=POSTGRES-PASSWORD-PLACEHOLDER
      - PG_META_CRYPTO_KEY=PG-META-CRYPTO-KEY-PLACEHOLDER
      - DEFAULT_ORGANIZATION_NAME=Deployrr
      - DEFAULT_PROJECT_NAME=${SUPABASE_PROJECT_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=http://supabase-kong:8000
      - SUPABASE_PUBLIC_URL=https://supabase.${DOMAINNAME_1}
      - SUPABASE_ANON_KEY=ANON-KEY-PLACEHOLDER
      - SUPABASE_SERVICE_KEY=SERVICE-ROLE-KEY-PLACEHOLDER
      - AUTH_JWT_SECRET=JWT-SECRET-PLACEHOLDER
      - LOGFLARE_API_KEY=LOGFLARE-PUBLIC-TOKEN-PLACEHOLDER
      - LOGFLARE_PUBLIC_ACCESS_TOKEN=LOGFLARE-PUBLIC-TOKEN-PLACEHOLDER
      - LOGFLARE_PRIVATE_ACCESS_TOKEN=LOGFLARE-PRIVATE-TOKEN-PLACEHOLDER
      - LOGFLARE_URL=http://supabase-analytics:4000
      - NEXT_PUBLIC_ENABLE_LOGS=true
      - NEXT_ANALYTICS_BACKEND_PROVIDER=postgres
      - SNIPPETS_MANAGEMENT_FOLDER=/app/snippets
      - EDGE_FUNCTIONS_MANAGEMENT_FOLDER=/app/edge-functions
    volumes:
      - $DOCKERDIR/appdata/supabase/volumes/snippets:/app/snippets:Z
      - $DOCKERDIR/appdata/supabase/volumes/functions:/app/edge-functions:Z
    # DOCKER-LABELS-PLACEHOLDER
