services:
  # Supabase Vector - Log Collector
  supabase-vector:
    container_name: supabase-vector
    image: timberio/vector:${SUPABASEVECTOR_VERSION_PIN}
    security_opt:
      - label:disable
    restart: unless-stopped
    profiles: ["apps", "all"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:9001/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/supabase/volumes/logs/vector.yml:/etc/vector/vector.yml:ro,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    environment:
      - LOGFLARE_PUBLIC_ACCESS_TOKEN=LOGFLARE-PUBLIC-TOKEN-PLACEHOLDER
    command: ["--config", "/etc/vector/vector.yml"]
    # DOCKER-LABELS-PLACEHOLDER
