services:
  # Supabase DB - PostgreSQL Database
  supabase-db:
    container_name: supabase-db
    image: supabase/postgres:${SUPABASEDB_VERSION_PIN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/supabase/volumes/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z
      - $DOCKERDIR/appdata/supabase/volumes/db/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql:Z
      - $DOCKERDIR/appdata/supabase-db/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST=/var/run/postgresql
      - PGPORT=5432
      - POSTGRES_PORT=5432
      - PGPASSWORD=POSTGRES-PASSWORD-PLACEHOLDER
      - POSTGRES_PASSWORD=POSTGRES-PASSWORD-PLACEHOLDER
      - PGDATABASE=postgres
      - POSTGRES_DB=postgres
      - JWT_SECRET=JWT-SECRET-PLACEHOLDER
      - JWT_EXP=3600
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal
    # DOCKER-LABELS-PLACEHOLDER
