services:
  # Nextcloud Redis - Dedicated Cache for Nextcloud
  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:${NEXTCLOUDREDIS_VERSION_PIN:-alpine}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/nextcloud-redis:/data
    # DOCKER-LABELS-PLACEHOLDER
