services: 
## rclone
  rclone:
    container_name: rclone
    image: wiserain/rclone
    restart: always
    networks:
      traefik_network:
    volumes:
      - /mnt/user/Docker/appdata/rclone_data/config:/config
      - /mnt/user/Docker/appdata/rclone_data/log:/log
      - /mnt/user/Docker/appdata/rclone_data/cache:/cache
      - /mnt/user/Docker/appdata/rclone_data/local:/local
      - /mnt/user/Docker/appdata/rclone_data/cloud:/cloud
      - /mnt/user/Docker/appdata/rclone_mount:/data:shared
      #- /local/dir/to/be/merged/with:/local     # Optional: if you have a folder to be mergerfs/unionfs with
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - RCLONE_REMOTE_PATH=PlexDrive:/
      - RCLONE_MOUNT_USER_OPTS=--allow-non-empty --bwlimit 16.5M:off --stats-one-line -P --stats 2s --vfs-disk-space-total-size 200T