services:
  # TeslaMate - Tesla Data Logger
  teslamate:
    image: ghcr.io/teslamate-org/teslamate:pr-4453
    container_name: teslamate
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - $TESLAMATE_PORT:4000
    volumes:
      - $DOCKERDIR/appdata/teslamate:/import:/opt/app/import
    environment:
      - ENCRYPTION_KEY=$TESLAMATE_ENCRYPTION_KEY
      - DATABASE_USER=$TESLAMATE_PGSQL_USER
      - DATABASE_PASS=$TESLAMATE_PGSQL_PASSWD
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-pgsql
      - MQTT_HOST=teslamate-mosquitto
      - MQTT_USERNAME=$TESLAMATE_MOSQUITTO_USERNAME
      - MQTT_PASSWORD=$TESLAMATE_MOSQUITTO_PASSWORD
    # DOCKER-LABELS-PLACEHOLDER