services:
  # Paperless-NGX MariaDB - Dedicated Database for Paperless-NGX
  paperless-ngx-mariadb:
    container_name: paperless-ngx-mariadb
    image: mariadb:${PAPERLESSNGXMARIADB_VERSION_PIN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/paperless-ngx-mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=$PAPERLESSNGX_MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=paperless
      - MARIADB_USER=paperlessngx_db_user
      - MARIADB_PASSWORD=$PAPERLESSNGX_MARIADB_PASSWORD
    # DOCKER-LABELS-PLACEHOLDER
