services:
  # Dockpeek - Lightweight Docker Dashboard
  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - socket_proxy
    ports:
      - "$DOCKPEEK_PORT:8000"
    environment:
      - SECRET_KEY=$DOCKPEEK_SECRET_KEY
      - USERNAME=$DOCKPEEK_USERNAME
      - PASSWORD=$DOCKPEEK_PASSWORD
      - DOCKER_HOST
      - DOCKER_HOST_NAME=$HOSTNAME
    # DOCKER-LABELS-PLACEHOLDER
