services:
  # Immich Database - PostgresQL Database for Immich
  immich-db:
    container_name: immich-db
    image: docker.io/tensorchord/pgvecto-rs:${IMMICHDB_VERSION_PIN}
    profiles: ["apps", "all"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    healthcheck:
      test: >-
        pg_isready --dbname="immich" --username="immich_db_user" || exit 1;
        Chksum="$$(psql --dbname="immich" --username="immich_db_user" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=off
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    environment:
      POSTGRES_PASSWORD: $IMMICHDB_POSTGRESQL_PASSWORD
      POSTGRES_USER: immich_db_user
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - $DOCKERDIR/appdata/immich-db:/var/lib/postgresql/data
    # DOCKER-LABELS-PLACEHOLDER