services:
  # Dockhand - Docker Container Management
  dockhand:
    image: fnsys/dockhand:${DOCKHAND_VERSION_PIN}
    container_name: dockhand
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      - socket_proxy
    depends_on:
      dockhand-postgresql:
        condition: service_healthy
    ports:
      - $DOCKHAND_PORT:3000/tcp
    volumes:
      - $DOCKERDIR/appdata/dockhand:/app/data
      # - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    environment:
      - DATABASE_URL=postgres://dockhand_db_user:$DOCKHAND_POSTGRESQL_PASSWORD@dockhand-postgresql:5432/dockhand
      - DOCKER_HOST
    # DOCKER-LABELS-PLACEHOLDER
