services:
  # Mosquitto - MQTT Broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    user: "${PUID}:0"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$MOSQUITTO_PORT:1883" #mqtt
      - "$MOSQUITTO_WS_PORT:9001" #websockets
    volumes:
      - $DOCKERDIR/appdata/mosquitto/config:/mosquitto/config
      - $DOCKERDIR/appdata/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/appdata/mosquitto/log:/mosquitto/log
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
